services:
  app:
    build:
      context: ./wonderful-chinese
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 9000:9000
    depends_on:
      - db
    env_file:
      - ./wonderful-chinese/.env
    volumes:
      - ./wonderful-chinese/storage:/usr/share/nginx/html/storage:rw
      - ./wonderful-chinese/public:/usr/share/nginx/html/public:rw
  queue-worker:
    build:
      context: ./wonderful-chinese
      dockerfile: Dockerfile
    restart: unless-stopped
    command: php artisan queue:work
    environment:
      IS_WORKER: "true"
    env_file:
      - ./wonderful-chinese/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./wonderful-chinese/storage:/usr/share/nginx/html/storage:rw
      - ./wonderful-chinese/public:/usr/share/nginx/html/public:rw
  nginx:
    image: nginx:1-alpine
    restart: unless-stopped
    ports:
      - 8008:80
      - 443:443
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./wonderful-chinese/storage:/usr/share/nginx/html/storage:rw
      - ./wonderful-chinese/public:/usr/share/nginx/html/public:ro
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 6603:3306
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: bitnami/redis:latest
    platform: linux/amd64
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis-data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
volumes:
  redis-data:
  db-data:
